include: package:effective_dart/analysis_options.1.2.0.yaml
linter:
  rules:
    prefer_relative_imports: false
    file_names: false
    omit_local_variable_types: false
    avoid_setters_without_getters: false
    lines_longer_than_80_chars: false
